/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HomePage.java
 *
 * Created on Feb 7, 2011, 4:24:28 PM
 */
package onlinedesktop;

import gui.AddIP;
import gui.CreateGroup;
import gui.NMGroup;
import gui.NMGroupIP;
import gui.ViewAllUsers;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JScrollPane;
import javax.swing.ImageIcon;

/**
 *
 * @author java
 */
public class HomePage extends javax.swing.JFrame {

    /** Creates new form HomePage */
    public static Container container;
    private static ServerSocket server;
    private Socket socket;
    public ImageIcon i;


    public HomePage() {
        container = this.getContentPane();
        container.setLayout(null);
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setTitle("Online Desktop");
        container.setBackground(Color.LIGHT_GRAY);
        System.out.println("MainFrame-----------------2");
        initComponents();
        container.removeAll();
        btnCreateGroup.setBounds(25, 15, 200, 50);
        btnViewGroup.setBounds(370, 15, 200, 50);
        btnAddIP.setBounds(705, 15, 200, 50);
        btnViewAll.setBounds(1020, 15, 200, 50);
        container.add(btnCreateGroup);
        container.add(btnViewGroup);
        container.add(btnAddIP);
        container.add(btnViewAll);
    }

    public HomePage(String str) {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateGroup = new javax.swing.JButton();
        btnViewGroup = new javax.swing.JButton();
        btnAddIP = new javax.swing.JButton();
        btnViewAll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnCreateGroup.setText("Create Group");
        btnCreateGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGroupActionPerformed(evt);
            }
        });

        btnViewGroup.setText("View Group");
        btnViewGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewGroupActionPerformed(evt);
            }
        });

        btnAddIP.setText("Add IP");
        btnAddIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIPActionPerformed(evt);
            }
        });

        btnViewAll.setText("View All");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinedesktop/remote-desktop-it-system.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel2.setText("Desktop Tracking");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddIP, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnViewGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnAddIP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(253, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGroupActionPerformed
        System.out.println("Create New Group");
        container.removeAll();
        CreateGroup obj = new CreateGroup();
        obj.setBounds(25, 100, 1200, 500);
        btnCreateGroup.setBounds(25, 15, 200, 50);
        btnViewGroup.setBounds(370, 15, 200, 50);
        btnAddIP.setBounds(705, 15, 200, 50);
        btnViewAll.setBounds(1020, 15, 200, 50);
        container.add(btnCreateGroup);
        container.add(btnViewGroup);
        container.add(btnAddIP);
        container.add(btnViewAll);
        container.add(obj);
        container.setVisible(false);
        container.setVisible(true);
    }//GEN-LAST:event_btnCreateGroupActionPerformed

    private void btnViewGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewGroupActionPerformed
        System.out.println("View Group");
        container.removeAll();

        //Add A panel with all the nm group name and event.
        NMGroup obj = new NMGroup();
        obj.setLayout(null);

        btnCreateGroup.setBounds(25, 15, 200, 50);
        btnViewGroup.setBounds(370, 15, 200, 50);


        btnAddIP.setBounds(705, 15, 200, 50);
        btnViewAll.setBounds(1020, 15, 200, 50);
        container.add(btnCreateGroup);
        container.add(btnViewGroup);
        container.add(btnAddIP);
        container.add(btnViewAll);
        obj.setVisible(true);

        obj.setPreferredSize(new Dimension(obj.getSize().width, 1000));
        JScrollPane sp = new JScrollPane(obj);
        sp.setSize(300, 500);
        sp.setVerticalScrollBarPolicy(sp.VERTICAL_SCROLLBAR_ALWAYS);
        //sp.setHorizontalScrollBarPolicy(sp.HORIZONTAL_SCROLLBAR_ALWAYS);
        sp.setVisible(true);

        sp.setBounds(25, 100, 200, 550);
        container.add(sp, BorderLayout.CENTER);


        //Panel having Online and Offline Users of a group.
        NMGroupIP groupIP = new NMGroupIP();
        groupIP.setLayout(null);
        groupIP.setVisible(true);
        groupIP.setPreferredSize(new Dimension(groupIP.getSize().width, 1000));
        sp = new JScrollPane(groupIP);
        sp.setVisible(true);
        sp.setBounds(368, 100, 860, 550);
        sp.setVerticalScrollBarPolicy(sp.VERTICAL_SCROLLBAR_ALWAYS);

        container.add(sp);
        new CommnicateJPanel(groupIP);

        container.setVisible(false);
        container.setVisible(true);
        container.setSize(400, 400);
        setLayout(null);
    }//GEN-LAST:event_btnViewGroupActionPerformed

    private void btnAddIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIPActionPerformed
        System.out.println("Create New Group");
        container.removeAll();
        AddIP obj = new AddIP();
        obj.setBounds(25, 100, 1200, 500);
        btnCreateGroup.setBounds(25, 15, 200, 50);
        btnViewGroup.setBounds(370, 15, 200, 50);
        btnAddIP.setBounds(705, 15, 200, 50);
        btnViewAll.setBounds(1020, 15, 200, 50);
        container.add(btnCreateGroup);
        container.add(btnViewGroup);
        container.add(btnAddIP);
        container.add(btnViewAll);
        container.add(obj);
        container.setVisible(false);
        container.setVisible(true);
    }//GEN-LAST:event_btnAddIPActionPerformed

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        System.out.println("View All Users");
        container.removeAll();
        ViewAllUsers obj = new ViewAllUsers();
        obj.setLayout(null);
        //obj.setBounds(25, 100, 1200, 500);
        btnCreateGroup.setBounds(25, 15, 200, 50);
        btnViewGroup.setBounds(370, 15, 200, 50);
        btnAddIP.setBounds(705, 15, 200, 50);
        btnViewAll.setBounds(1020, 15, 200, 50);
        container.add(btnCreateGroup);
        container.add(btnViewGroup);
        container.add(btnAddIP);
        container.add(btnViewAll);

        obj.setPreferredSize(new Dimension(obj.getSize().width, 1000));
        JScrollPane sp = new JScrollPane(obj);
        //sp.setSize(300, 500);
        sp.setVerticalScrollBarPolicy(sp.VERTICAL_SCROLLBAR_ALWAYS);
        //sp.setHorizontalScrollBarPolicy(sp.HORIZONTAL_SCROLLBAR_ALWAYS);
        sp.setVisible(true);
        sp.setBounds(25, 100, 1200, 500);

        container.add(sp);
        container.setVisible(false);
        container.setVisible(true);
    }//GEN-LAST:event_btnViewAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HomePage().setVisible(true);
            }
        });
        try {
            server = new ServerSocket(8888);
        } catch (Exception e) {
            System.out.println("HomePage Exception --------- " + e);
        }
        new OnlineClientList().getOnlineClient(server);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddIP;
    private javax.swing.JButton btnCreateGroup;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JButton btnViewGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
